name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      env:
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
        CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
        
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## What's Changed
          
          This release includes the latest features and improvements for Naptrix Sleep Tracker.
          
          ### Features
          - Sleep tracking and analytics
          - Modern UI with responsive design
          - Secure authentication with Clerk
          - Real-time data visualization
          
          ### Technical Details
          - Built with Next.js 15 and React 19
          - TypeScript for type safety
          - Tailwind CSS for styling
          - Prisma ORM with PostgreSQL
          
          Full Changelog: ${{ github.event.repository.compare_url }}
        draft: false
        prerelease: false
